language: node_js

dist: trusty

node_js:
  - '10'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

# after_failure:
#   - bash ./scripts/sendscreenshots.sh

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache

jobs:
  include:
    - stage: 'Prepare cache'
      script: true
    - stage: 'Tests'
      name: 'Static linting'
      script: yarn lint
    - script: yarn test:coverage
      name: 'Unit Tests'
    - script: yarn test:dms:e2e
      addons:
        chrome: stable
