language: node_js

dist: trusty

addons:
  chrome: stable

node_js:
  - '10'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache

script:
  - yarn
  - yarn build
  - yarn test:dms:e2e
