on: [pull_request]

name: cd

jobs:
  deploy-snapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install
        run: yarn install

      - name: build
        run: yarn build

      - name: build snapp
        run: yarn snapp build

        - name: Publish
          uses: netlify/actions/cli@master
            with:
              args: deploy --dir=./apps/sensenet/build --message ${{ github.event.pull_request.number }}
          env:
	          NETLIFY_SITE_ID: 94fb346c-b540-40f7-aaaf-21eee2a9c891
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
