on: [push]

name: ci

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install
        run: yarn install
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: lint
        run: yarn lint

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install
        run: yarn install
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: build
        run: yarn build

      - name: build examples
        run: yarn build:examples

      - name: build snapp
        run: yarn snapp build
        env:
          RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}

      - name: test
        run: NODE_OPTIONS='--max-old-space-size=4096' yarn test --coverage

      - uses: codecov/codecov-action@v1
