on: [pull_request]

name: deploy preview

jobs:
  deploy-snapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get commit message
        run: |
          echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})

      - uses: actions/cache@v1
        if: "!contains( env.commitmsg , 'skip-deploy' )"
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install
        if: "!contains( env.commitmsg , 'skip-deploy' )"
        run: yarn install
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: build
        if: "!contains( env.commitmsg , 'skip-deploy' )"
        run: yarn build

      - name: build snapp
        if: "!contains( env.commitmsg , 'skip-deploy' )"
        run: yarn snapp build
        env:
          RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}

      - name: wake up deploy notifier
        if: "!contains( env.commitmsg , 'skip-deploy' )"
        run: yarn wait-on https://sensenet-sn-deploy-notifier.glitch.me/ -l -t 300000

      - name: Publish
        if: "!contains( env.commitmsg , 'skip-deploy' )"
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=./apps/sensenet/build --message ${{ github.event.pull_request.number }}
        env:
          NETLIFY_SITE_ID: 94fb346c-b540-40f7-aaaf-21eee2a9c891
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get commit message
        run: |
          echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})

      - uses: actions/cache@v1
        if: "!contains( env.commitmsg , 'skip-deploy' )"
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install
        if: "!contains( env.commitmsg , 'skip-deploy' )"
        run: yarn install
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: build
        if: "!contains( env.commitmsg , 'skip-deploy' )"
        run: yarn build

      - name: build storybook
        if: "!contains( env.commitmsg , 'skip-deploy' )"
        run: yarn storybook build-storybook

      - name: wake up deploy notifier
        if: "!contains( env.commitmsg , 'skip-deploy' )"
        run: yarn wait-on https://sensenet-sn-deploy-notifier.glitch.me/ -l -t 300000

      - name: Publish
        if: "!contains( env.commitmsg , 'skip-deploy' )"
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=./examples/sn-react-component-docs/storybook-static --message ${{ github.event.pull_request.number }}
        env:
          NETLIFY_SITE_ID: 1747b330-27d8-4ddd-bf74-39469c257010
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
