on: [push, pull_request]

name: lint & test

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: upgrade yarn
        run: npm install yarn -g

      - uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install
        run: yarn install

      - name: build
        run: yarn build

      - name: lint
        run: yarn lint

      - name: test
        run: yarn test:coverage

      - uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
